version: '3.6'
services:
  server:
    image: mtijnnl/domoticz-ubiquity:1.3.0
    secrets:
      - source: unifi-env
        target: /app/.env
        mode: 0400

secrets:
  unifi-env:
    external: true
